from typing import Protocol, Any, Iterable, Dict

class ZoteroClientProtocol(Protocol):
    def items(self) -> Iterable[Dict[str, Any]]: ...
    def collections(self) -> Iterable[Dict[str, Any]]: ...
    def collection_items(self, collection_key: str) -> Iterable[Dict[str, Any]]: ...

