from typing import Protocol, TypeVar, Optional, Iterable

T = TypeVar("T")

class StorageProtocol(Protocol[T]):
    def count(self) -> int: ...
    def all(self) -> Iterable[T]: ...
    def fill(self, items: Iterable[T]) -> None: ...
    def reset(self) -> None: ...
    def append(self, item: T) -> None: ...
    def remove_at(self, row: int) -> None: ...
    def replace_at(self, row: int, item: T) -> None: ...
    def at(self, row: int) -> Optional[T]: ...
    def in_bounds(self, row: int) -> bool: ...
    def flush(self) -> None: ...
