from typing import Protocol, TypeVar, Optional, Iterable

T = TypeVar("T")

class DataListStorageProtocol(Protocol[T]):
    def count(self) -> int: ...
    def all(self) -> Iterable[T]: ...
    def fill(self, _items: Iterable[T]) -> None: ...
    def append(self, _item: T) -> None: ...
    def remove_at(self, _index: int) -> None: ...
    def replace_at(self, _index: int, _item: T) -> None: ...
    def at(self, _index: int) -> Optional[T]: ...
    def in_bounds(self, _index: int) -> bool: ...
